name: bun-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: bun-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Test
        run: bun run test:bun
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
