name: publish-docs

on:
  workflow_dispatch:
  release:
    types: [created]

concurrency:
  group: docs
  cancel-in-progress: false

jobs:
  build:
    name: publish-docs
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          ref: main
          owner: clashperk
          repo: clashofclans.js.org
          wait_interval: 10
          wait_workflow: true
          trigger_workflow: true
          propagate_failure: false
          workflow_file_name: deploy-github-pages.yml
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
