name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Docs (Staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Docs Repository
        uses: actions/checkout@v2
        with:
          repository: clashperk/clashofclans.js.org

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: lib

      - name: Copy CHANGELOG.md
        run: cp lib/CHANGELOG.md docs/changelog.md

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          working-directory: ./build
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}